# Ejercicio 9

> Por: Mapachana

**Toma n tu número publicado para el ejer_ 2. Escríbe n en base 2, usa esas cifras para definir un polinomio, f(x), donde tu bit más significativo defina el grado del polinomio n, el siguiente bit va multiplicado por $x^{n-1}$ y sucesivamente hasta que el bit menos significativo sea el término independiente.El polinomio que obtienes es universal en el sentido de que tiene coeficientes en cualquier anillo**

**Sea f(x) el polinomio que obtienes con coeficientes en $\mathbb{Z}$**

In [1]:
n = 77770081
print(n)
n.binary()

77770081


'100101000101010110101100001'

In [2]:
import numpy as np

In [19]:
Z2 = PolynomialRing(GF(2), 'x')
x = Z2.gen()
g = x^26+x^23+x^21+x^17+x^15+x^13+x^11+x^10+x^8+x^6+x^5+1
print(g)

x^26 + x^23 + x^21 + x^17 + x^15 + x^13 + x^11 + x^10 + x^8 + x^6 + x^5 + 1


**i) Toma g(x) = f(x) mod 2 y halla el menor cuerpo de característica 2 que contenga a todas las raíces de g. ¿ Qué deduces sobre la irreducibilidad de g(x) en $\mathbb{Z}_2[x]$ ?.**

In [23]:
def menor_cuerpo(modulo, p, x):
    g = x^p
    g1 = (g-x).mod(modulo)
    k = 1
    
    while g1 != 0:
        g = (g^p).mod(modulo)
        g1 = (g - x).mod(modulo)
        k = k + 1
        
    print(k)
    return k
        

In [24]:
# Ejemplo profe
menor_cuerpo(1+x+x^2+x^3+x^4+x^6+x^7+x^8+x^10+x^11+x^14, 2, x)
# Ejemplo wuolah
menor_cuerpo(x^26+x^23+x^21+x^15+x^14+x^11+x^8+x^7+x^6+x^2+1, 2, x)

33
153


153

In [41]:
menor_cuerpo(g, 2, x)

46


46

In [42]:
factor(46)

2 * 23

El menor cuerpo de característica 2 que contiene a todas las raíces de $g$ es $F_{2^{46}}=F_{2^{2\cdot 23}}$. Como tenemos que $46>26$ entonces $g(x)$ es reducible en $\mathbb{Z}_2[x]$. Además, sabemos que los factores en los que se descomponga $g$ serán de grado un divisor de $46$, esto es, $1$, $2$ o $23$. 

In [43]:
g.is_irreducible()

False

**ii) Extrae la parte libre de cuadrados de g(x) y le calculas su matriz de Berlekamp por columnas. Resuelve el s.l. (B-Id)X=0.**

In [44]:
print(g)
print(g.derivative())
print(gcd(g, g.derivative()))

x^26 + x^23 + x^21 + x^17 + x^15 + x^13 + x^11 + x^10 + x^8 + x^6 + x^5 + 1
x^22 + x^20 + x^16 + x^14 + x^12 + x^10 + x^4
1


Tenemos que el máximo común divisor de $g$ y su derivada es $(g, g')=1$, luego $g$ es libre de cuadrados. Pasamos por tanto a calcular su matriz de Berlekamp por columnas:

In [47]:
def calcular_B(g, p, cuerpo):
    # g esta definido sobre cuerpo (en nuestro caso Z2 o Z3)
    x = cuerpo.gen()
    B = np.zeros([g.degree(), g.degree()], dtype = int)

    for i in range(0, g.degree()):
        coeficientes = [0] * g.degree()

        pol = (x^(p*i)).mod(g)
        #pol = pol.mod(g)
        print("[" + str(i) + "] x^2i mod f = " + str(pol))

        for j, coef in enumerate(pol.coefficients(sparse = False)):
            coeficientes[j] = coef

        B[i, :] = coeficientes
    return Matrix(cuerpo, B.tolist())

#B = calcular_B(g, 2, Z2)


In [51]:
# Ejemplo diapos
print(calcular_B(x^5+x^2+1, 2, Z2))
print()
# Ejemplo wuolah
print(calcular_B(x^26+x^23+x^21+x^15+x^14+x^11+x^8+x^7+x^6+x^2+1, 2, Z2))

[0] x^2i mod f = 1
[1] x^2i mod f = x^2
[2] x^2i mod f = x^4
[3] x^2i mod f = x^3 + x
[4] x^2i mod f = x^3 + x^2 + 1
[1 0 0 0 0]
[0 0 1 0 0]
[0 0 0 0 1]
[0 1 0 1 0]
[1 0 1 1 0]

[0] x^2i mod f = 1
[1] x^2i mod f = x^2
[2] x^2i mod f = x^4
[3] x^2i mod f = x^6
[4] x^2i mod f = x^8
[5] x^2i mod f = x^10
[6] x^2i mod f = x^12
[7] x^2i mod f = x^14
[8] x^2i mod f = x^16
[9] x^2i mod f = x^18
[10] x^2i mod f = x^20
[11] x^2i mod f = x^22
[12] x^2i mod f = x^24
[13] x^2i mod f = x^23 + x^21 + x^15 + x^14 + x^11 + x^8 + x^7 + x^6 + x^2 + 1
[14] x^2i mod f = x^25 + x^23 + x^17 + x^16 + x^13 + x^10 + x^9 + x^8 + x^4 + x^2
[15] x^2i mod f = x^25 + x^24 + x^22 + x^19 + x^18 + x^16 + x^11 + x^10 + x^9 + x^8 + x^7 + x^6 + x^4 + x^3 + x
[16] x^2i mod f = x^23 + x^22 + x^20 + x^18 + x^16 + x^14 + x^13 + x^10 + x^8 + x^5 + x^2 + x + 1
[17] x^2i mod f = x^25 + x^24 + x^22 + x^20 + x^18 + x^16 + x^15 + x^12 + x^10 + x^7 + x^4 + x^3 + x^2
[18] x^2i mod f = x^23 + x^21 + x^20 + x^18 + x^17 + x^16 + x^11 +

In [52]:
B = calcular_B(g, 2, Z2)

[0] x^2i mod f = 1
[1] x^2i mod f = x^2
[2] x^2i mod f = x^4
[3] x^2i mod f = x^6
[4] x^2i mod f = x^8
[5] x^2i mod f = x^10
[6] x^2i mod f = x^12
[7] x^2i mod f = x^14
[8] x^2i mod f = x^16
[9] x^2i mod f = x^18
[10] x^2i mod f = x^20
[11] x^2i mod f = x^22
[12] x^2i mod f = x^24
[13] x^2i mod f = x^23 + x^21 + x^17 + x^15 + x^13 + x^11 + x^10 + x^8 + x^6 + x^5 + 1
[14] x^2i mod f = x^25 + x^23 + x^19 + x^17 + x^15 + x^13 + x^12 + x^10 + x^8 + x^7 + x^2
[15] x^2i mod f = x^25 + x^24 + x^22 + x^21 + x^19 + x^18 + x^17 + x^16 + x^15 + x^11 + x^10 + x^7 + x^6 + x^4 + x
[16] x^2i mod f = x^22 + x^20 + x^19 + x^16 + x^15 + x^14 + x^10 + x^7 + x^6 + x^5 + x^3 + x + 1
[17] x^2i mod f = x^24 + x^22 + x^21 + x^18 + x^17 + x^16 + x^12 + x^9 + x^8 + x^7 + x^5 + x^3 + x^2
[18] x^2i mod f = x^24 + x^21 + x^20 + x^19 + x^18 + x^17 + x^15 + x^14 + x^13 + x^9 + x^8 + x^7 + x^6 + x^4 + 1
[19] x^2i mod f = x^22 + x^20 + x^19 + x^16 + x^13 + x^9 + x^5 + x^2 + 1
[20] x^2i mod f = x^24 + x^22 + x^21 + x^1

In [53]:
print(B)

[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[1 0 0 0 0 1 1 0 1 0 1 1 0 1 0 1 0 1 0 0 0 1 0 1 0 0]
[0 0 1 0 0 0 0 1 1 0 1 0 1 1 0 1 0 1 0 1 0 0 0 1 0 1]
[0 1 0 0 1 0 1 1 0 0 1 1 0 0 0 1 1 1 1 1 0 1 1 0 1 1]
[1 1 0 1 0 1 1 1 0 0 1 0 0 0 1 1 1 0 0 1 1 0 1 0 0 0]
[0 0 1 1 0 1 0 1 1 1 0 0 1 0 0 0 1 1 1 0 0 1 1 0 1 0]
[1 0 0 0 1 0 1 1 1 1 0 0 0 1

Ahora que tenemos construida B, vamos a resolver (B-Id)X=0

In [57]:
Id = Matrix.identity(g.degree())
print(B.rank())
print((B-Id).rank())


26
23


El rango de B-Id es 23, luego la dimensión de $V_1=26-23=3$. Por tanto, hay $3$ soluciones.

In [69]:
Ka = (calcular_B(x^5+x+1, 2, Z2)-Matrix.identity(5)).left_kernel()
print(Ka)

# Ejemplo wuolah
Ka = (calcular_B(x^26+x^23+x^21+x^15+x^14+x^11+x^8+x^7+x^6+x^2+1, 2, Z2)-Id).left_kernel()
print(Ka)

[0] x^2i mod f = 1
[1] x^2i mod f = x^2
[2] x^2i mod f = x^4
[3] x^2i mod f = x^2 + x
[4] x^2i mod f = x^4 + x^3
Free module of degree 5 and rank 2 over Univariate Polynomial Ring in x over Finite Field of size 2 (using GF2X)
Echelon basis matrix:
[1 0 0 0 0]
[0 1 0 1 1]
[0] x^2i mod f = 1
[1] x^2i mod f = x^2
[2] x^2i mod f = x^4
[3] x^2i mod f = x^6
[4] x^2i mod f = x^8
[5] x^2i mod f = x^10
[6] x^2i mod f = x^12
[7] x^2i mod f = x^14
[8] x^2i mod f = x^16
[9] x^2i mod f = x^18
[10] x^2i mod f = x^20
[11] x^2i mod f = x^22
[12] x^2i mod f = x^24
[13] x^2i mod f = x^23 + x^21 + x^15 + x^14 + x^11 + x^8 + x^7 + x^6 + x^2 + 1
[14] x^2i mod f = x^25 + x^23 + x^17 + x^16 + x^13 + x^10 + x^9 + x^8 + x^4 + x^2
[15] x^2i mod f = x^25 + x^24 + x^22 + x^19 + x^18 + x^16 + x^11 + x^10 + x^9 + x^8 + x^7 + x^6 + x^4 + x^3 + x
[16] x^2i mod f = x^23 + x^22 + x^20 + x^18 + x^16 + x^14 + x^13 + x^10 + x^8 + x^5 + x^2 + x + 1
[17] x^2i mod f = x^25 + x^24 + x^22 + x^20 + x^18 + x^16 + x^15 + x^12 + x

In [70]:
# AX=C
A = B-Id
print(A.parent())
C = vector(GF(2), [0] * g.degree())
print(C.parent())

K = A.left_kernel()

print(K)



Full MatrixSpace of 26 by 26 dense matrices over Univariate Polynomial Ring in x over Finite Field of size 2 (using GF2X)
Vector space of dimension 26 over Finite Field of size 2
Free module of degree 26 and rank 3 over Univariate Polynomial Ring in x over Finite Field of size 2 (using GF2X)
Echelon basis matrix:
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 1 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1 1 0]
[0 0 1 0 0 1 0 1 0 0 0 0 1 1 0 0 1 1 0 0 1 0 0 0 0 1]


Luego obtenemos los polinomios:
$$f_1(x) = 1$$
$$f_2(x) = x+x^3+x^4+x^5+x^6+x^{10}+x^{12}+x^{14}+x^{16}+x^{18}+x^{19}+x^{23}+x^{24}$$
$$f_3(x) = x^2+x^5+x^7+x^{12}+x^{13}+x^{16}+x^{17}+x^{20}+x^{25}$$

In [71]:
f1 = 1
f2 = x+x^3+x^4+x^5+x^6+x^10+x^12+x^14+x^16+x^18+x^19+x^23+x^24
f3 = x^2+x^5+x^7+x^12+x^13+x^16+x^17+x^20+x^25

In [76]:
print(gcd(g, f1))
div = gcd(g, f1)
a = g/div
print(a)
print(a*div)
if (a*div == g):
    print("COINCIDE")
print()

print(gcd(g, f2))
div = gcd(g, f2)
a = g/div
print(a)
print(a*div)
if (a*div == g):
    print("COINCIDE")
print()

print(gcd(g, f3))
div = gcd(g, f3)
a = g/div
print(a)
print(a*div)
if (a*div == g):
    print("COINCIDE")
print()

1
x^26 + x^23 + x^21 + x^17 + x^15 + x^13 + x^11 + x^10 + x^8 + x^6 + x^5 + 1
x^26 + x^23 + x^21 + x^17 + x^15 + x^13 + x^11 + x^10 + x^8 + x^6 + x^5 + 1
COINCIDE

x^2 + x + 1
x^24 + x^23 + x^19 + x^18 + x^16 + x^14 + x^12 + x^10 + x^6 + x^5 + x^4 + x^3 + x + 1
x^26 + x^23 + x^21 + x^17 + x^15 + x^13 + x^11 + x^10 + x^8 + x^6 + x^5 + 1
COINCIDE

x^23 + x^18 + x^15 + x^14 + x^11 + x^10 + x^5 + x^3 + 1
x^3 + 1
x^26 + x^23 + x^21 + x^17 + x^15 + x^13 + x^11 + x^10 + x^8 + x^6 + x^5 + 1
COINCIDE



Creo que tenemos que $f_2$ y $f_3$ son g-reductores. Pero no se hace asi, faltan cosas y va en el siguiente apartado creo

**iii) Aplica Berlekamp si es necesario recursivamente para hallar la descomposiciónen irreducibles de g(x) en $\mathbb{Z}_2[x]$.**

**iv) Haz lo mismo para hallar la descomposición en irreducibles de f(x) mod 3**

**v) ¿ Qué deduces sobre la reducibilidad de f(x) en $\mathbb{Z}[x]$ ?**