# Ejercicio 9

> Por: Mapachana

**Toma n tu número publicado para el ejer_ 2. Escríbe n en base 2, usa esas cifras para definir un polinomio, f(x), donde tu bit más significativo defina el grado del polinomio n, el siguiente bit va multiplicado por $x^{n-1}$ y sucesivamente hasta que el bit menos significativo sea el término independiente.El polinomio que obtienes es universal en el sentido de que tiene coeficientes en cualquier anillo**

**Sea f(x) el polinomio que obtienes con coeficientes en $\mathbb{Z}$**

In [73]:
n = 77770081
print(n)
n.binary()

77770081


'100101000101010110101100001'

In [74]:
import numpy as np

In [75]:
Z2 = PolynomialRing(GF(2), 'x')
x = Z2.gen()
g = x^26+x^23+x^21+x^17+x^15+x^13+x^11+x^10+x^8+x^6+x^5+1
print(g)

x^26 + x^23 + x^21 + x^17 + x^15 + x^13 + x^11 + x^10 + x^8 + x^6 + x^5 + 1


**i) Toma g(x) = f(x) mod 2 y halla el menor cuerpo de característica 2 que contenga a todas las raíces de g. ¿ Qué deduces sobre la irreducibilidad de g(x) en $\mathbb{Z}_2[x]$ ?.**

In [76]:
def menor_cuerpo(modulo, p, x):
    g = x^p
    g1 = (g-x).mod(modulo)
    k = 1
    
    while g1 != 0:
        g = (g^p).mod(modulo)
        g1 = (g - x).mod(modulo)
        k = k + 1
        
    print(k)
    return k
        

In [77]:
# Ejemplo profe
menor_cuerpo(1+x+x^2+x^3+x^4+x^6+x^7+x^8+x^10+x^11+x^14, 2, x)
# Ejemplo wuolah
menor_cuerpo(x^26+x^23+x^21+x^15+x^14+x^11+x^8+x^7+x^6+x^2+1, 2, x)
# Ejemplo mio
menor_cuerpo(x^2+x, 2, x)

33
153
1


1

In [78]:
menor_cuerpo(g, 2, x)

46


46

In [79]:
factor(46)

2 * 23

El menor cuerpo de característica 2 que contiene a todas las raíces de $g$ es $F_{2^{46}}=F_{2^{2\cdot 23}}$. Como tenemos que $46>26$ entonces $g(x)$ es reducible en $\mathbb{Z}_2[x]$. Además, sabemos que los factores en los que se descomponga $g$ serán de grado un divisor de $46$, esto es, $1$, $2$ o $23$. 

In [80]:
g.is_irreducible()

False

**ii) Extrae la parte libre de cuadrados de g(x) y le calculas su matriz de Berlekamp por columnas. Resuelve el s.l. (B-Id)X=0.**

In [81]:
print(g)
print(g.derivative())
print(gcd(g, g.derivative()))

x^26 + x^23 + x^21 + x^17 + x^15 + x^13 + x^11 + x^10 + x^8 + x^6 + x^5 + 1
x^22 + x^20 + x^16 + x^14 + x^12 + x^10 + x^4
1


Tenemos que el máximo común divisor de $g$ y su derivada es $(g, g')=1$, luego $g$ es libre de cuadrados. Pasamos por tanto a calcular su matriz de Berlekamp por columnas:

In [82]:
def calcular_B(g, p, cuerpo):
    # g esta definido sobre cuerpo (en nuestro caso Z2 o Z3)
    x = cuerpo.gen()
    B = np.zeros([g.degree(), g.degree()], dtype = int)

    for i in range(0, g.degree()):
        coeficientes = [0] * g.degree()

        pol = (x^(p*i)).mod(g)
        #pol = pol.mod(g)
        print("[" + str(i) + "] x^2i mod f = " + str(pol))

        for j, coef in enumerate(pol.coefficients(sparse = False)):
            coeficientes[j] = coef

        B[i, :] = coeficientes
    return Matrix(cuerpo, B.tolist())

#B = calcular_B(g, 2, Z2)


In [83]:
# Ejemplo diapos
print(calcular_B(x^5+x^2+1, 2, Z2))
print()
# Ejemplo wuolah
print(calcular_B(x^26+x^23+x^21+x^15+x^14+x^11+x^8+x^7+x^6+x^2+1, 2, Z2))

[0] x^2i mod f = 1
[1] x^2i mod f = x^2
[2] x^2i mod f = x^4
[3] x^2i mod f = x^3 + x
[4] x^2i mod f = x^3 + x^2 + 1
[1 0 0 0 0]
[0 0 1 0 0]
[0 0 0 0 1]
[0 1 0 1 0]
[1 0 1 1 0]

[0] x^2i mod f = 1
[1] x^2i mod f = x^2
[2] x^2i mod f = x^4
[3] x^2i mod f = x^6
[4] x^2i mod f = x^8
[5] x^2i mod f = x^10
[6] x^2i mod f = x^12
[7] x^2i mod f = x^14
[8] x^2i mod f = x^16
[9] x^2i mod f = x^18
[10] x^2i mod f = x^20
[11] x^2i mod f = x^22
[12] x^2i mod f = x^24
[13] x^2i mod f = x^23 + x^21 + x^15 + x^14 + x^11 + x^8 + x^7 + x^6 + x^2 + 1
[14] x^2i mod f = x^25 + x^23 + x^17 + x^16 + x^13 + x^10 + x^9 + x^8 + x^4 + x^2
[15] x^2i mod f = x^25 + x^24 + x^22 + x^19 + x^18 + x^16 + x^11 + x^10 + x^9 + x^8 + x^7 + x^6 + x^4 + x^3 + x
[16] x^2i mod f = x^23 + x^22 + x^20 + x^18 + x^16 + x^14 + x^13 + x^10 + x^8 + x^5 + x^2 + x + 1
[17] x^2i mod f = x^25 + x^24 + x^22 + x^20 + x^18 + x^16 + x^15 + x^12 + x^10 + x^7 + x^4 + x^3 + x^2
[18] x^2i mod f = x^23 + x^21 + x^20 + x^18 + x^17 + x^16 + x^11 +

In [84]:
B = calcular_B(g, 2, Z2)

[0] x^2i mod f = 1
[1] x^2i mod f = x^2
[2] x^2i mod f = x^4
[3] x^2i mod f = x^6
[4] x^2i mod f = x^8
[5] x^2i mod f = x^10
[6] x^2i mod f = x^12
[7] x^2i mod f = x^14
[8] x^2i mod f = x^16
[9] x^2i mod f = x^18
[10] x^2i mod f = x^20
[11] x^2i mod f = x^22
[12] x^2i mod f = x^24
[13] x^2i mod f = x^23 + x^21 + x^17 + x^15 + x^13 + x^11 + x^10 + x^8 + x^6 + x^5 + 1
[14] x^2i mod f = x^25 + x^23 + x^19 + x^17 + x^15 + x^13 + x^12 + x^10 + x^8 + x^7 + x^2
[15] x^2i mod f = x^25 + x^24 + x^22 + x^21 + x^19 + x^18 + x^17 + x^16 + x^15 + x^11 + x^10 + x^7 + x^6 + x^4 + x
[16] x^2i mod f = x^22 + x^20 + x^19 + x^16 + x^15 + x^14 + x^10 + x^7 + x^6 + x^5 + x^3 + x + 1
[17] x^2i mod f = x^24 + x^22 + x^21 + x^18 + x^17 + x^16 + x^12 + x^9 + x^8 + x^7 + x^5 + x^3 + x^2
[18] x^2i mod f = x^24 + x^21 + x^20 + x^19 + x^18 + x^17 + x^15 + x^14 + x^13 + x^9 + x^8 + x^7 + x^6 + x^4 + 1
[19] x^2i mod f = x^22 + x^20 + x^19 + x^16 + x^13 + x^9 + x^5 + x^2 + 1
[20] x^2i mod f = x^24 + x^22 + x^21 + x^1

In [85]:
print(B)

[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[1 0 0 0 0 1 1 0 1 0 1 1 0 1 0 1 0 1 0 0 0 1 0 1 0 0]
[0 0 1 0 0 0 0 1 1 0 1 0 1 1 0 1 0 1 0 1 0 0 0 1 0 1]
[0 1 0 0 1 0 1 1 0 0 1 1 0 0 0 1 1 1 1 1 0 1 1 0 1 1]
[1 1 0 1 0 1 1 1 0 0 1 0 0 0 1 1 1 0 0 1 1 0 1 0 0 0]
[0 0 1 1 0 1 0 1 1 1 0 0 1 0 0 0 1 1 1 0 0 1 1 0 1 0]
[1 0 0 0 1 0 1 1 1 1 0 0 0 1

Ahora que tenemos construida B, vamos a resolver (B-Id)X=0

In [86]:
Id = Matrix.identity(g.degree())
print(B.rank())
print((B-Id).rank())


26
23


El rango de B-Id es 23, luego la dimensión de $V_1=26-23=3$. Por tanto, hay $3$ soluciones.

In [87]:
Ka = (calcular_B(x^5+x+1, 2, Z2)-Matrix.identity(5)).left_kernel()
print(Ka)

# Ejemplo wuolah
Ka = (calcular_B(x^26+x^23+x^21+x^15+x^14+x^11+x^8+x^7+x^6+x^2+1, 2, Z2)-Id).left_kernel()
print(Ka)

[0] x^2i mod f = 1
[1] x^2i mod f = x^2
[2] x^2i mod f = x^4
[3] x^2i mod f = x^2 + x
[4] x^2i mod f = x^4 + x^3
Free module of degree 5 and rank 2 over Univariate Polynomial Ring in x over Finite Field of size 2 (using GF2X)
Echelon basis matrix:
[1 0 0 0 0]
[0 1 0 1 1]
[0] x^2i mod f = 1
[1] x^2i mod f = x^2
[2] x^2i mod f = x^4
[3] x^2i mod f = x^6
[4] x^2i mod f = x^8
[5] x^2i mod f = x^10
[6] x^2i mod f = x^12
[7] x^2i mod f = x^14
[8] x^2i mod f = x^16
[9] x^2i mod f = x^18
[10] x^2i mod f = x^20
[11] x^2i mod f = x^22
[12] x^2i mod f = x^24
[13] x^2i mod f = x^23 + x^21 + x^15 + x^14 + x^11 + x^8 + x^7 + x^6 + x^2 + 1
[14] x^2i mod f = x^25 + x^23 + x^17 + x^16 + x^13 + x^10 + x^9 + x^8 + x^4 + x^2
[15] x^2i mod f = x^25 + x^24 + x^22 + x^19 + x^18 + x^16 + x^11 + x^10 + x^9 + x^8 + x^7 + x^6 + x^4 + x^3 + x
[16] x^2i mod f = x^23 + x^22 + x^20 + x^18 + x^16 + x^14 + x^13 + x^10 + x^8 + x^5 + x^2 + x + 1
[17] x^2i mod f = x^25 + x^24 + x^22 + x^20 + x^18 + x^16 + x^15 + x^12 + x

In [88]:
# AX=C
A = B-Id
print(A.parent())
C = vector(GF(2), [0] * g.degree())
print(C.parent())

K = A.left_kernel()

print(K)



Full MatrixSpace of 26 by 26 dense matrices over Univariate Polynomial Ring in x over Finite Field of size 2 (using GF2X)
Vector space of dimension 26 over Finite Field of size 2
Free module of degree 26 and rank 3 over Univariate Polynomial Ring in x over Finite Field of size 2 (using GF2X)
Echelon basis matrix:
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 1 0 1 1 1 1 0 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1 1 0]
[0 0 1 0 0 1 0 1 0 0 0 0 1 1 0 0 1 1 0 0 1 0 0 0 0 1]


Luego obtenemos los polinomios:
$$f_1(x) = 1$$
$$f_2(x) = x+x^3+x^4+x^5+x^6+x^{10}+x^{12}+x^{14}+x^{16}+x^{18}+x^{19}+x^{23}+x^{24}$$
$$f_3(x) = x^2+x^5+x^7+x^{12}+x^{13}+x^{16}+x^{17}+x^{20}+x^{25}$$

In [89]:
f1 = 1
f2 = x+x^3+x^4+x^5+x^6+x^10+x^12+x^14+x^16+x^18+x^19+x^23+x^24
f3 = x^2+x^5+x^7+x^12+x^13+x^16+x^17+x^20+x^25

Creo que tenemos que $f_2$ y $f_3$ son g-reductores. Pero no se hace asi, faltan cosas y va en el siguiente apartado creo

**iii) Aplica Berlekamp si es necesario recursivamente para hallar la descomposiciónen irreducibles de g(x) en $\mathbb{Z}_2[x]$.**

Comenzamos trabajando con $f_2$, para el que calculamos $(g, f_2) =h_1$ y $(g, f_2+1)=h_2$ y comprobamos si son libres de cuadrados:

In [90]:
h1 = gcd(g, f2)
h2 = gcd(g, f2+1)
print("(g, f2) = {}".format(h1))
print("(g, f2+1) = {}".format(h2))

print(gcd(h1, h1.derivative()))
print(gcd(h2, h2.derivative()))

if g == h1*h2:
    print("COINCIDE")
    
print(h1.is_irreducible())
print(h2.is_irreducible())

h2.factor()
g.factor()

menor_cuerpo(h2, 2, x)

(g, f2) = x^2 + x + 1
(g, f2+1) = x^24 + x^23 + x^19 + x^18 + x^16 + x^14 + x^12 + x^10 + x^6 + x^5 + x^4 + x^3 + x + 1
1
1
COINCIDE
True
False
23


23

Luego tenemos que $g=h_1\cdot h_2$.
Por el apartado 1, sabemos además que la descomposición debe venir dada por polinomios cuyo grado sea divisor de 46, es decir, 1, 2 o 23. Como $h_2$ tiene grado 24 y el menor cuerpo de característica 2 que lo contiene es $F_{2^{23}}$, con 23<24, no sabemos si debe ser reducible. En efecto, tenemos que $h_2$ tiene 1 como raíz y por tanto descompone como 
$$h_2=(x+1)\cdot (x^{23}+x^{18}+x^{15}+x^{14}+x^{11}+x^{10}+x^5+x^3+1)$$

Luego la descomposición en irreducibles de $g$ es:
$$g=(x+1)\cdot (x^2+x+1) \cdot (x^{23}+x^{18}+x^{15}+x^{14}+x^{11}+x^{10}+x^5+x^3+1)$$

Hacemos lo análogo con $f_3$, considerando $(g, f_3) =h_3$ y $(g, f_3+1)=h_4$ 

In [91]:
h3 = gcd(g, f3)
h4 = gcd(g, f3+1)
print("(g, f3) = {}".format(h3))
print("(g, f3+1) = {}".format(h4))

print(gcd(h3, h3.derivative()))
print(gcd(h4, h4.derivative()))

if g == h3*h4:
    print("COINCIDE")
    
print(h3.is_irreducible())
print(h4.is_irreducible())

h4.factor()
menor_cuerpo(h4, 2, x)

(g, f3) = x^23 + x^18 + x^15 + x^14 + x^11 + x^10 + x^5 + x^3 + 1
(g, f3+1) = x^3 + 1
1
1
COINCIDE
True
False
2


2

Obteniendo por tanto que $g=h_3\cdot h_4$

De nuevo, observamos que $h_4$ tiene grado 4 y el menor cuerpo de característica 2 que lo contiene es $F_{2^{2}}$, luego no sabemos si es reducible, si lo fuera, tendría un factor de grado 1 y otro de grado 2, y en efecto $h_4=(x+1)\cdot x^2+x+1)$, pues 1 es raíz suyo, y la descomposición de $g$ en irreducibles resulta:

$$g=(x+1)\cdot (x^2+x+1) \cdot (x^{23}+x^{18}+x^{15}+x^{14}+x^{11}+x^{10}+x^5+x^3+1)$$


**iv) Haz lo mismo para hallar la descomposición en irreducibles de f(x) mod 3**

In [92]:
menor_cuerpo(y^26+y^23+y^21+y^15+y^14+y^11+y^8+y^7+y^6+y^2+1, 3, y)

56


56

In [93]:
Z3 = PolynomialRing(GF(3), 'y')
y = Z3.gen()
h = y^26+y^23+y^21+y^17+y^15+y^13+y^11+y^10+y^8+y^6+y^5+1

print(gcd(h, h.derivative()))

print(menor_cuerpo(h, 3, y))

print(117.factor())

1
117
117
3^2 * 13


Tenemos que $f \mod 3 =g= h = x^{26} + x^{23} + x^{21} + x^{17} + x^{15} + x^{13} + x^{11} + x^{10} + x^8 + x^6 + x^5 + 1$

Tenemos que $(g, g')=1$, luego $h$ es libre de cuadrados.

El menor cuerpo de característica 3 que contiene las raíces de $h$ es $F_{3^{117}}=F_{3^{3^2\cdot 13}}$, y como $117>26$ tenemos que $h$ es reducible, con factores de grado 1, 3, 9 o 13.

Calculamos ahora la matriz B por columnas:


In [94]:
B = calcular_B(h, 3, Z3)
print(B)

[0] x^2i mod f = 1
[1] x^2i mod f = y^3
[2] x^2i mod f = y^6
[3] x^2i mod f = y^9
[4] x^2i mod f = y^12
[5] x^2i mod f = y^15
[6] x^2i mod f = y^18
[7] x^2i mod f = y^21
[8] x^2i mod f = y^24
[9] x^2i mod f = 2*y^24 + 2*y^22 + 2*y^18 + 2*y^16 + 2*y^14 + 2*y^12 + 2*y^11 + 2*y^9 + 2*y^7 + 2*y^6 + 2*y
[10] x^2i mod f = 2*y^25 + y^24 + y^22 + 2*y^21 + 2*y^19 + y^18 + 2*y^17 + y^16 + 2*y^15 + y^11 + 2*y^10 + y^7 + y^6 + 2*y^4 + y
[11] x^2i mod f = 2*y^25 + y^24 + y^23 + y^22 + y^21 + 2*y^20 + 2*y^19 + y^18 + y^17 + 2*y^16 + y^15 + 2*y^11 + 2*y^10 + y^8 + 2*y^7 + 2*y^6 + y^4 + y^2 + 2*y
[12] x^2i mod f = 2*y^25 + 2*y^23 + y^22 + y^20 + 2*y^16 + y^14 + 2*y^13 + 2*y^11 + 2*y^10 + y^9 + y^7 + y^6 + 2*y^4 + y^2 + 2*y + 2
[13] x^2i mod f = 2*y^25 + y^21 + 2*y^16 + 2*y^15 + 2*y^14 + y^13 + 2*y^12 + y^11 + y^9 + 2*y^8 + y^6 + 2*y^5 + 2*y^4 + 2*y^3 + y^2 + 1
[14] x^2i mod f = y^25 + y^24 + y^23 + 2*y^18 + y^16 + y^14 + y^13 + 2*y^12 + 2*y^11 + y^10 + y^9 + 2*y^6 + y^5 + y^3 + y^2
[15] x^2i mod f = 2

Como (B-Id) tiene rango 22, entonces $26-22=4$ tendremos 4 soluciones.
Y resolvemos el sistema (B-Id)X=0

In [95]:
Id = Matrix.identity(h.degree())
print(B.rank())
print((B-Id).rank())

# AX=C
A = B-Id
print(A.parent())
C = vector(GF(3), [0] * h.degree())
print(C.parent())

K = A.left_kernel()

print(K)

26
22
Full MatrixSpace of 26 by 26 dense matrices over Univariate Polynomial Ring in y over Finite Field of size 3
Vector space of dimension 26 over Finite Field of size 3
Free module of degree 26 and rank 4 over Univariate Polynomial Ring in y over Finite Field of size 3
Echelon basis matrix:
[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 2 0 1 1 1 1 2 1 1 0 1 1 0 1 0 2 2 0 0 1 1 2 0 1 0]
[0 0 1 2 0 2 1 0 2 0 1 1 2 1 0 1 0 1 2 1 1 2 2 2 0 0]
[0 0 0 0 1 2 0 1 0 1 2 0 1 0 1 2 2 2 2 1 0 0 2 0 0 1]


Obtenemos los siguientes polinomios:

$$f_1 = 1$$
$$f_2 = 2*y+y^3+y^4+y^5+y^6+2*y^7+y^8+y^9+y^{11}+y^{12}+y^{14}+2*y^{16}+2*y^{17}+y^{20}+y^{21}+2*y^{22}+y^{24}$$
$$f_3 = y^2+2*y^3+2*y^5+y^6+2*y^8+y^{10}+y^{11}+2*y^{12}+y^{13}+y^{15}+y^{17}+2*y^{18}+y^{19}+y^{20}+2*y^{21}+2*y^{22}+2*y^{23}$$
$$f_4 = y^4+2*y^5+y^7+y^9+2*y^{10}+y^{12}+y^{14}+2*y^{15}+2*y^{16}+2*y^{17}+2*y^{18}+y^{19}+2*y^{22}+y^{25}$$

In [96]:
f1 = 1
f2 = 2*y+y^3+y^4+y^5+y^6+2*y^7+y^8+y^9+y^11+y^12+y^14+2*y^16+2*y^17+y^20+y^21+2*y^22+y^24
f3 = y^2+2*y^3+2*y^5+y^6+2*y^8+y^10+y^11+2*y^12+y^13+y^15+y^17+2*y^18+y^19+y^20+2*y^21+2*y^22+2*y^23
f4 = y^4+2*y^5+y^7+y^9+2*y^10+y^12+y^14+2*y^15+2*y^16+2*y^17+2*y^18+y^19+2*y^22+y^25

In [97]:
h1 = gcd(h, f2)
h2 = gcd(h, f2+1)
h3 = gcd(h, f2+2)
print("(g, f2) = {}".format(h1))
print("(g, f2+1) = {}".format(h2))
print("(g, f2+2) = {}".format(h3))

print(gcd(h1, h1.derivative()))
print(gcd(h2, h2.derivative()))
print(gcd(h3, h3.derivative()))

if h == h1*h2*h3:
    print("COINCIDE")
    
print(h1.is_irreducible())
print(h2.is_irreducible())
print(h3.is_irreducible())

menor_cuerpo(h1, 3, y)
menor_cuerpo(h2, 3, y)
menor_cuerpo(h3, 3, y)

print(h3)
print(h3.factor())

haux = y^9 + 2*y^7 + 2*y^6 + 2*y^5 + 2*y^3 + y + 1
menor_cuerpo(haux, 3, y)
print(haux.is_irreducible())

(g, f2) = y^3 + 2*y^2 + 1
(g, f2+1) = y^13 + 2*y^12 + y^11 + y^10 + 2*y^9 + 2*y^8 + 2*y^7 + y^5 + y^4 + y^2 + 2
(g, f2+2) = y^10 + 2*y^9 + 2*y^8 + y^5 + 2*y^4 + y^3 + y^2 + 2
1
1
1
COINCIDE
True
True
False
3
13
9
y^10 + 2*y^9 + 2*y^8 + y^5 + 2*y^4 + y^3 + y^2 + 2
(y + 2) * (y^9 + 2*y^7 + 2*y^6 + 2*y^5 + 2*y^3 + y + 1)
9
True


Obtenemos por tanto que $h=h_1\cdot h_2\cdot h_3$, y como el mínimo cuerpo de característica 3 que contiene las raíces de $h_1$ es 3, coincidiendo con su grado, se tiene que es irreducible. Análogamente se tiene que para $h_2$ es 13, y por tanto es irreducible. Mientras para $h_3$ es 9, distinto de su grado, y es fácil comprobar que tiene 1 como raíz simple, luego se descompone en $h_3=(x+2)\cdot (y^9+2y^7+2y^6+2y^5+2y^3+y+1)$, luego la descomposición de $h$ en irreducibles es:

$$h = (y^3 + 2y^2 + 1)\cdot (y^{13} + 2y^{12} + y^{11} + y^{10} + 2*y^9 + 2*y^8 + 2*y^7 + y^5 + y^4 + y^2 + 2)\cdot (y+2)\cdot (y^9 + 2y^7 + 2y^6 + 2y^5 + 2y^3 + y + 1)$$

In [98]:
h4 = gcd(h, f3)
h5 = gcd(h, f3+1)
h6 = gcd(h, f3+2)
print("(g, f3) = {}".format(h4))
print("(g, f3+1) = {}".format(h5))
print("(g, f3+2) = {}".format(h6))

print(gcd(h4, h4.derivative()))
print(gcd(h5, h5.derivative()))
print(gcd(h6, h6.derivative()))

if h == h4*h5*h6:
    print("COINCIDE")
    
print(h4.is_irreducible())
print(h5.is_irreducible())
print(h6.is_irreducible())

menor_cuerpo(h4, 3, y)
menor_cuerpo(h5, 3, y)
menor_cuerpo(h6, 3, y)

print(h4.factor())

(g, f3) = y^16 + y^15 + 2*y^14 + y^13 + y^11 + y^10 + 2*y^7 + 2*y^6 + 2*y^5 + 2*y^3 + 2*y^2 + 2
(g, f3+1) = y^9 + 2*y^7 + 2*y^6 + 2*y^5 + 2*y^3 + y + 1
(g, f3+2) = y + 2
1
1
1
COINCIDE
False
True
True
39
9
1
(y^3 + 2*y^2 + 1) * (y^13 + 2*y^12 + y^11 + y^10 + 2*y^9 + 2*y^8 + 2*y^7 + y^5 + y^4 + y^2 + 2)


Obtenemos por tanto que $h=h_4\cdot h_5\cdot h_6$, y como el mínimo cuerpo de característica 3 que contiene las raíces de $h_5$ es 9, coincidiendo con su grado, se tiene que es irreducible. Análogamente se tiene que para $h_6$ es 1, y por tanto es irreducible. Mientras para $h_4$ es 39, mayor de su grado, y por tanto aplicamos el algoritmo de nuevo a este polinomio.

In [99]:
B = calcular_B(h4, 3, Z3)
print(B)

Id = Matrix.identity(h4.degree())
print(B.rank())
print((B-Id).rank())

# AX=C
A = B-Id
print(A.parent())
C = vector(GF(3), [0] * h4.degree())
print(C.parent())

K = A.left_kernel()

print(K)

[0] x^2i mod f = 1
[1] x^2i mod f = y^3
[2] x^2i mod f = y^6
[3] x^2i mod f = y^9
[4] x^2i mod f = y^12
[5] x^2i mod f = y^15
[6] x^2i mod f = 2*y^15 + 2*y^11 + y^10 + y^9 + 2*y^7 + y^6 + y^3 + 2*y + 2
[7] x^2i mod f = y^15 + 2*y^14 + y^13 + y^12 + y^11 + y^10 + y^7 + 2*y^4 + y^3 + y + 1
[8] x^2i mod f = y^14 + 2*y^13 + y^12 + y^11 + y^9 + 2*y^8 + 2*y^7 + 2*y^5 + 2*y^2 + y + 1
[9] x^2i mod f = y^15 + y^14 + 2*y^13 + y^10 + 2*y^7 + 2*y^6 + 2*y^4 + y^2 + y + 1
[10] x^2i mod f = 2*y^15 + 2*y^12 + 2*y^10 + y^8 + 2*y^5 + 2*y^4 + y^3 + y^2
[11] x^2i mod f = 2*y^13 + 2*y^11 + 2*y^10 + 2*y^9 + 2*y^8 + y^5 + 2*y^3 + y + 1
[12] x^2i mod f = y^15 + y^14 + 2*y^12 + y^10 + y^8 + 2*y^7 + y^6 + 2*y^5 + y^4 + 2*y^2 + 2
[13] x^2i mod f = y^14 + 2*y^13 + 2*y^12 + y^10 + 2*y^9 + y^6 + y^5 + y^4 + 2*y^2 + 1
[14] x^2i mod f = 2*y^15 + y^12 + y^11 + 2*y^10 + y^9 + 2*y^8 + 2*y^6 + y^4 + y^2 + y + 1
[15] x^2i mod f = 2*y^15 + y^14 + 2*y^13 + y^12 + 2*y^10 + y^9 + 2*y^7 + 2*y^6 + y^5 + y^4 + y + 1
[1 0 0 0 0 0

Luego obtenemos el polinomio $f_5=y+2*y^3+2*y^5+2*y^6+y^8+y^9+y^{10}+2*y^{11}+2*y^{12}+y^{13}+2*y^{14}$

In [109]:
f5 = y+2*y^3+2*y^5+2*y^6+y^8+y^9+y^10+2*y^11+2*y^12+y^13+2*y^14

h10 = gcd(h4, f5)
h11 = gcd(h4, f5+1)
h12 = gcd(h4, f5+2)
print("(g, f5) = {}".format(h10))
print("(g, f5+1) = {}".format(h11))
print("(g, f5+2) = {}".format(h12))

print(gcd(h10, h10.derivative()))
print(gcd(h11, h11.derivative()))
print(gcd(h12, h12.derivative()))

if h4 == h10*h11*h12:
    print("COINCIDE")
    
print(h10.is_irreducible())
print(h11.is_irreducible())
print(h12.is_irreducible())

menor_cuerpo(h10, 3, y)
menor_cuerpo(h11, 3, y)
menor_cuerpo(h12, 3, y)

(g, f5) = y^13 + 2*y^12 + y^11 + y^10 + 2*y^9 + 2*y^8 + 2*y^7 + y^5 + y^4 + y^2 + 2
(g, f5+1) = 1
(g, f5+2) = y^3 + 2*y^2 + 1
1
1
1
COINCIDE
True
False
True
13
1
3


3

Obtenemos lso polinomios $h_{10}, h_{11}. h_{12}$ y todos ellos son irreducibles. Por tanto $h_4=h_{10}\cdot h_{11}\cdot h_{12}$ es su descomposición en irreducibles y la de h queda como:
$$h = (y^3 + 2y^2 + 1)\cdot (y^{13} + 2y^{12} + y^{11} + y^{10} + 2*y^9 + 2*y^8 + 2*y^7 + y^5 + y^4 + y^2 + 2)\cdot (y+2)\cdot (y^9 + 2y^7 + 2y^6 + 2y^5 + 2y^3 + y + 1)$$

In [110]:
h7 = gcd(h, f4)
h8 = gcd(h, f4+1)
h9 = gcd(h, f4+2)
print("(g, f4) = {}".format(h7))
print("(g, f4+1) = {}".format(h8))
print("(g, f4+2) = {}".format(h9))

print(gcd(h7, h7.derivative()))
print(gcd(h8, h8.derivative()))
print(gcd(h9, h9.derivative()))

if h == h7*h8*h9:
    print("COINCIDE")
    
print(h7.is_irreducible())
print(h8.is_irreducible())
print(h9.is_irreducible())

menor_cuerpo(h7, 3, y)
menor_cuerpo(h8, 3, y)
menor_cuerpo(h9, 3, y)

print(h8.factor())

(g, f4) = y + 2
(g, f4+1) = y^22 + 2*y^21 + y^19 + y^18 + y^17 + 2*y^15 + y^14 + 2*y^13 + y^12 + 2*y^11 + 2*y^10 + y^9 + 2*y^8 + y^7 + 2*y^6 + 2*y^5 + y^4 + 2*y^3 + y^2 + 2*y + 2
(g, f4+2) = y^3 + 2*y^2 + 1
1
1
1
COINCIDE
True
False
True
1
117
3
(y^9 + 2*y^7 + 2*y^6 + 2*y^5 + 2*y^3 + y + 1) * (y^13 + 2*y^12 + y^11 + y^10 + 2*y^9 + 2*y^8 + 2*y^7 + y^5 + y^4 + y^2 + 2)


Obtenemos por tanto que $h=h_7\cdot h_8\cdot h_9$, y como el mínimo cuerpo de característica 3 que contiene las raíces de $h_7$ es 1, coincidiendo con su grado, se tiene que es irreducible. Análogamente se tiene que para $h_9$ es 3, y por tanto es irreducible. Mientras para $h_8$ es 117, mayor de su grado, y por tanto aplicamos el algoritmo de nuevo a este polinomio.

In [111]:
B = calcular_B(h8, 3, Z3)
print(B)

Id = Matrix.identity(h8.degree())
print(B.rank())
print((B-Id).rank())

# AX=C
A = B-Id
print(A.parent())
C = vector(GF(3), [0] * h8.degree())
print(C.parent())

K = A.left_kernel()

print(K)

#[0 0 2 1 1            1 1 1 1 1         0 1 0 0 1          0 2 0 2 1        2 0]
f6 = 2*y^2+y^3+y^4+y^5+y^6+y^7+y^8+y^9+y^11+y^14+2*y^16+2*y^18+y^19+2*y^20

h13 = gcd(h8, f6)
h14 = gcd(h8, f6+1)
h15 = gcd(h8, f6+2)
print("(g, f6) = {}".format(h13))
print("(g, f6+1) = {}".format(h14))
print("(g, f6+2) = {}".format(h15))

print(gcd(h13, h13.derivative()))
print(gcd(h14, h14.derivative()))
print(gcd(h15, h15.derivative()))

if h8 == h13*h14*h15:
    print("COINCIDE")
    
print(h13.is_irreducible())
print(h14.is_irreducible())
print(h15.is_irreducible())

menor_cuerpo(h13, 3, y)
menor_cuerpo(h14, 3, y)
menor_cuerpo(h15, 3, y)

[0] x^2i mod f = 1
[1] x^2i mod f = y^3
[2] x^2i mod f = y^6
[3] x^2i mod f = y^9
[4] x^2i mod f = y^12
[5] x^2i mod f = y^15
[6] x^2i mod f = y^18
[7] x^2i mod f = y^21
[8] x^2i mod f = y^20 + y^18 + y^15 + 2*y^14 + y^13 + y^12 + y^11 + y^10 + 2*y^9 + y^8 + y^7 + y^6 + y^5 + 2*y^4 + y^3 + y^2 + 2*y + 1
[9] x^2i mod f = 2*y^21 + 2*y^20 + y^19 + 2*y^18 + y^17 + 2*y^16 + y^15 + y^14 + y^13 + 2*y^12 + y^10 + y^9 + y^8 + 2*y^7 + y^5 + 2*y^4 + y^3 + 2*y + 1
[10] x^2i mod f = 2*y^21 + y^20 + y^18 + y^17 + 2*y^15 + y^13 + 2*y^12 + 2*y^11 + 2*y^10 + y^8 + 2*y^6 + 2*y^4 + y^3 + y^2 + 2
[11] x^2i mod f = 2*y^21 + 2*y^20 + y^19 + 2*y^18 + 2*y^17 + 2*y^16 + y^15 + y^13 + 2*y^12 + 2*y^11 + 2*y^10 + 2*y^8 + y^7 + 2*y^6 + y^4 + y^3 + 2*y^2
[12] x^2i mod f = 2*y^21 + 2*y^20 + y^18 + 2*y^15 + 2*y^14 + 2*y^13 + y^12 + y^10 + 2*y^9 + 2*y^7 + 2*y^6 + 2*y^5 + y^2 + 2
[13] x^2i mod f = 2*y^19 + y^16 + y^14 + y^12 + y^10 + y^8 + 2*y^7 + y^4 + y^3 + 2*y^2 + 2*y + 1
[14] x^2i mod f = 2*y^21 + 2*y^19 + y^18 + 2

9

Luego obtenemos el polinomio $f_6=2*y^2+y^3+y^4+y^5+y^6+y^7+y^8+y^9+y^11+y^14+2*y^16+2*y^18+y^19+2*y^20$

Obtenemos lso polinomios $h_{13}, h_{14}. h_{15}$ y todos ellos son irreducibles. Por tanto $h_8=h_{13}\cdot h_{14}\cdot h_{15}$ es su descomposición en irreducibles y la de h queda como:
$$h = (y^3 + 2y^2 + 1)\cdot (y^{13} + 2y^{12} + y^{11} + y^{10} + 2*y^9 + 2*y^8 + 2*y^7 + y^5 + y^4 + y^2 + 2)\cdot (y+2)\cdot (y^9 + 2y^7 + 2y^6 + 2y^5 + 2y^3 + y + 1)$$

**v) ¿ Qué deduces sobre la reducibilidad de f(x) en $\mathbb{Z}[x]$ ?**

Como $g$ descompone en $\mathbb{Z}_2[x]$ en 3 polinomios irreducibles de grados 1, 2 y 23, y en $\mathbb{Z}_3[x]$ en 4 polinomios irreducibles de grados 1, 3, 9 y 13, tenemos que las factorizaciones son incompatibles y por tanto $g$ es irreducible en $\mathbb{Z}[x]$

In [113]:
print(g.factor())
print(h.factor())

(x + 1) * (x^2 + x + 1) * (x^23 + x^18 + x^15 + x^14 + x^11 + x^10 + x^5 + x^3 + 1)
(y + 2) * (y^3 + 2*y^2 + 1) * (y^9 + 2*y^7 + 2*y^6 + 2*y^5 + 2*y^3 + y + 1) * (y^13 + 2*y^12 + y^11 + y^10 + 2*y^9 + 2*y^8 + 2*y^7 + y^5 + y^4 + y^2 + 2)
